language: csharp
solution: MSOE.MediaComplete.sln
script:
  - xbuild /p:Configuration=Debug MSOE.MediaComplete.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore MSOE.MediaComplete.sln
after_script:
  - nunit-console MSOE.MediaComplete.Test/bin/x86/Debug/MSOE.MediaComplete.Test.dll
